### ISSUE TITLE
thanks，nice~~

### ISSUE THREAD

**Issue by swift-fs** [vassbo/pdf2img-electron#1]
I've been working on the electron solution all afternoon, and it's either too old or it won't run

**Comment by vassbo** [comment]
Could you explain further what you mean?

**Comment by vassbo** [comment]
It should work. Do you get any errors in the console? And have you tried with different PDFs?

**Comment by swift-fs** [comment]
> It should work. Do you get any errors in the console? And have you tried with different PDFs?


Your library operates efficiently, but exporting PDFs in a continuous loop on the Mac frequently encounters timeouts.  Works well on windows（electron 32.0.0）。

**Comment by swift-fs** [comment]
```typescript
 async parsePdf(pdfPath: string) {
    const PDF = pdf(pdfPath);
    console.log('[ pdf pages ] >', PDF.pages);
    if (PDF.pages == 0) {
      return null;
    }

    const imageBuffers = await PDF.toPNG({ scale: 1, pages: [0], timeout: 10000 });
    //console.log(imageBuffers);
    if (imageBuffers.length == 0) {
      return null;
    }
    const image = imageBuffers[0];
    const text = await this.ocr(image);

    return text;
  }
```

Dummy code example:

```typescript
for (let index = 0; index < paths.length; index++) {
  await parsePdf(paths[index])
}
````

Converting multiple pdf2img in a for loop is ok on windows and often times out on mac 2019 i5 processors

**Comment by vassbo** [comment]
Thanks, I see. I don't have a mac at this point in time so I can't debug it. I would like this to get fixed though.

Do you think you are able to debug the issue?

**Comment by swift-fs** [comment]
> Thanks, I see. I don't have a mac at this point in time so I can't debug it. I would like this to get fixed though.谢谢，我明白了。我目前没有 mac，所以无法调试它。不过我希望这个问题能够得到解决。
> 
> Do you think you are able to debug the issue?您认为您能够调试该问题吗？

It should be fine. I'll check it out

**Comment by vassbo** [comment]
Hi @swift-fs, did you manage to figure anything out?

**Comment by swift-fs** [comment]
> Hi @swift-fs, did you manage to figure anything out?嗨，您有没有弄清楚什么？
Yesterday the customer's win10 also appeared the same problem, I want to check

**Comment by vassbo** [comment]
All right, I think it's related to the PDF just getting completely stuck at a grey screen loading sometimes, and not continuing loading. There are some checks for that, that should reload the entire page, but sometimes it might fail. I think it might be a chromium issue, but also there should be a way to avoid it.

**Comment by swift-fs** [comment]
> All right, I think it's related to the PDF just getting completely stuck at a grey screen loading sometimes, and not continuing loading. There are some checks for that, that should reload the entire page, but sometimes it might fail. I think it might be a chromium issue, but also there should be a way to avoid it.好吧，我认为这与 PDF 有时完全卡在灰屏加载中，并且不继续加载有关。有一些检查应该重新加载整个页面，但有时它可能会失败。我认为这可能是一个 chromium 问题，但也应该有办法避免它。

You are right, I tried to write a simple to img, without too much checking, is completely feasible. (However, now it has changed the scheme and uses mupdfjs~~~)

**Comment by vassbo** [comment]
Okay, closing this if you switched to [mupdfjs](https://www.npmjs.com/package/mupdf). It looks good, but need 11 MB of extra space.
